[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "cython>=0.25",
    "numpy>2",
    "pytest-runner"
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--ignore=docs"
